private: add encoding declarations.
This improves error message with Python 2.

Before:

   $ python2.7 private/collect-characters --help
     File "private/collect-characters", line 3
   SyntaxError: Non-ASCII character '\xc2' in file private/collect-characters on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

After:

    $ python2.7 private/collect-characters --help
      File "private/collect-characters", line 33
        int(0_0)  # Python >= 3.6 is required
              ^
    SyntaxError: invalid syntax