lib.cli: use the "fork" multiprocessing start method.
In Python 3.14, multiprocessing switched to "forkserver" as the default
start method, but our code is not ready for that:

    $ i18nspector -j2 *.po
    Traceback (most recent call last):
      ...
    RuntimeError:
            An attempt has been made to start a new process before the
            current process has finished its bootstrapping phase.

            This probably means that you are not using fork to start your
            child processes and you have forgotten to use the proper idiom
            in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce an executable.

            To fix this issue, refer to the "Safe importing of main module"
            section in https://docs.python.org/3/library/multiprocessing.html

    Traceback (most recent call last):
      ...
    ConnectionResetError: [Errno 104] Connection reset by peer

Switch back to the "fork" method for now.

https://github.com/jwilk/i18nspector/issues/20

https://github.com/python/cpython/issues/84559